{
	"version": 1575858380,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/bnovojogo-sheet0.png",
		"images/fase1.png",
		"images/personagem-sheet0.png",
		"images/personagem-sheet1.png",
		"images/personagem-sheet2.png",
		"images/blocoinimigo-sheet0.png",
		"images/hp-sheet0.png",
		"images/bgaleria-sheet0.png",
		"images/bcreditos-sheet0.png",
		"images/bsair-sheet0.png",
		"images/entrada-sheet0.png",
		"images/tilemap.png",
		"images/tilemap2.png",
		"images/postotexto-sheet0.png",
		"images/placa-sheet0.png",
		"images/blocopersonagem-sheet0.png",
		"images/temposhow.png",
		"images/viafechada-sheet0.png",
		"images/detalhes.png",
		"images/plaquinha-sheet0.png",
		"images/plaquinha-sheet1.png",
		"images/powerupcontroller-sheet0.png",
		"images/powerupcontroller-sheet1.png",
		"images/colisao_speed-sheet0.png",
		"images/pressz-sheet0.png",
		"images/buracos-sheet0.png",
		"images/logo-sheet0.png",
		"images/particulasmenu.png",
		"images/glow-sheet0.png",
		"images/cartinhahepatiteb-sheet0.png",
		"images/cartinhainfluenza-sheet0.png",
		"images/cartinhatriplice-sheet0.png",
		"images/dooencas-sheet0.png",
		"images/botaovoltar-sheet0.png",
		"images/telabvitoria-sheet0.png",
		"images/sadtela-sheet0.png",
		"images/fase-sheet0.png",
		"images/fase3-sheet0.png",
		"images/fase4-sheet0.png",
		"images/preto-sheet0.png",
		"images/trofeufase1-sheet0.png",
		"images/trofeufase1-sheet1.png",
		"images/fasebloqueada-sheet0.png",
		"images/tutorial-sheet0.png",
		"images/caixadetexti-sheet0.png",
		"images/carsdestroh-sheet0.png",
		"images/carro-sheet0.png",
		"images/powerspawner-sheet0.png",
		"images/triste-sheet0.png",
		"images/gameoverrrr-sheet0.png",
		"images/happyilust-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sdg-sheet0.png",
		"media/som_acertou.m4a",
		"media/som_acertou.ogg",
		"media/som_botão (2).m4a",
		"media/som_botão (2).ogg",
		"media/som_botão.m4a",
		"media/som_botão.ogg",
		"media/som_derrota.m4a",
		"media/som_derrota.ogg",
		"media/som_passos.m4a",
		"media/som_passos.ogg",
		"media/220173__gameaudio__spacey-1up-power-up (1).m4a",
		"media/220173__gameaudio__spacey-1up-power-up (1).ogg",
		"media/371897__josepharaoh99__paper-crinkle.m4a",
		"media/371897__josepharaoh99__paper-crinkle.ogg",
		"media/50561__broumbroum__sf3-sfx-menu-select.m4a",
		"media/50561__broumbroum__sf3-sfx-menu-select.ogg",
		"media/agente vacina.m4a",
		"media/agente vacina.ogg",
		"media/flaremain.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}