{
	"version": 1555535384,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/caixadedialogo-sheet0.png",
		"images/chão-sheet0.png",
		"images/playa-sheet0.png",
		"images/npctutori-sheet0.png",
		"images/npctutori-sheet1.png",
		"images/zone2tuori-sheet0.png",
		"images/playadestructed-sheet0.png",
		"images/spritefont.png",
		"images/tiledbackground.png",
		"images/savepoint-sheet0.png",
		"images/visualplaya-sheet0.png",
		"images/visualplaya-sheet1.png",
		"images/healthbar-sheet0.png",
		"images/healthhealth-sheet0.png",
		"images/coisamalvada-sheet0.png",
		"images/coisadobem-sheet0.png",
		"images/sprite-sheet0.png",
		"images/scroolto-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/inimigo1projetil-sheet0.png",
		"images/inimigo1projetil-sheet1.png",
		"images/opa-sheet0.png",
		"images/tilemap.png",
		"images/solid-sheet0.png",
		"images/crack-sheet0.png",
		"images/plataformadeteste-sheet0.png",
		"images/tilemap4.png",
		"images/inimigo1-sheet0.png",
		"images/balita-sheet0.png",
		"images/balita-sheet1.png",
		"images/batatas-sheet0.png",
		"images/inimigo2-sheet0.png",
		"images/inimigo2projetil-sheet0.png",
		"images/spike-sheet0.png",
		"images/eventminiboss1-sheet0.png",
		"images/miniboss1-sheet0.png",
		"images/miniboss1-sheet1.png",
		"images/miniboss1-sheet2.png",
		"images/bosswall-sheet0.png",
		"images/miniboss1projectile-sheet0.png",
		"images/teleport1-sheet0.png",
		"images/keyteleport12-sheet0.png",
		"images/jumpthing-sheet0.png",
		"images/move-sheet0.png",
		"images/atac-sheet0.png",
		"images/spacesave-sheet0.png",
		"images/pretaodomenu-sheet0.png",
		"images/tutorialtofase1-sheet0.png",
		"images/boss1-sheet0.png",
		"images/ultrauvaboss-sheet0.png",
		"images/ultrauvaboss-sheet1.png",
		"images/bossprojetil-sheet0.png",
		"images/bossprojetil-sheet1.png",
		"images/bossprojetil-sheet2.png",
		"images/purify-sheet0.png",
		"images/coisinhadobem-sheet0.png",
		"images/hpmaxmais-sheet0.png",
		"images/hpmaxmais-sheet1.png",
		"images/bg-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite7-sheet1.png",
		"images/inimigo4-sheet0.png",
		"images/miniboss2-sheet0.png",
		"images/coisonadobem-sheet0.png",
		"images/trap-sheet0.png",
		"images/spawntrap-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/inimigo4projetil-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/stopsetinha-sheet0.png",
		"images/cidadehojept20181025_-sheet0.png",
		"images/spawn-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/aaa-sheet0.png",
		"images/inibgood-sheet0.png",
		"images/corruptedinib-sheet0.png",
		"images/limit-sheet0.png",
		"images/barpercent-sheet0.png",
		"images/percentinib.png",
		"images/kit-sheet0.png",
		"images/spacetosave-sheet0.png",
		"images/gamesaved-sheet0.png",
		"images/aura-sheet0.png",
		"images/aura-sheet1.png",
		"images/bubbles-sheet0.png",
		"images/bubbles-sheet1.png",
		"images/bubbles-sheet2.png",
		"images/sprite15-sheet0.png",
		"images/sprite16-sheet0.png",
		"images/sprite17-sheet0.png",
		"images/pitchukinhahead-sheet0.png",
		"images/fase1bloco-sheet0.png",
		"images/fase2bloco-sheet0.png",
		"images/fase3bloco-sheet0.png",
		"images/area-sheet0.png",
		"images/tree-sheet0.png",
		"images/tree2-sheet0.png",
		"images/tree3-sheet0.png",
		"images/tree4-sheet0.png",
		"images/sprite19-sheet0.png",
		"images/sprite20-sheet0.png",
		"images/sprite21-sheet0.png",
		"images/sprite22-sheet0.png",
		"images/eventofada-sheet0.png",
		"images/fada-sheet0.png",
		"images/fada-sheet1.png",
		"images/fada-sheet2.png",
		"images/posicaofada-sheet0.png",
		"images/72572029_p1_master-sheet0.png",
		"images/sprite23-sheet0.png",
		"images/menusplashu-sheet0.png",
		"images/eredfactory-sheet0.png",
		"images/sprite25-sheet0.png",
		"images/primrose-sheet0.png",
		"images/primroses-sheet0.png",
		"images/anykey-sheet0.png",
		"images/seta-sheet0.png",
		"images/esc-sheet0.png",
		"images/continue-sheet0.png",
		"images/exit-sheet0.png",
		"images/paused-sheet0.png",
		"images/z-sheet0.png",
		"images/newgame-sheet0.png",
		"images/options-sheet0.png",
		"images/credit-sheet0.png",
		"images/marromoverlap-sheet0.png",
		"images/continueapdddeta-sheet0.png",
		"images/escuridau-sheet0.png",
		"images/escreveakigiselleeee-sheet0.png",
		"images/bacc-sheet0.png",
		"images/felicia-sheet0.png",
		"images/contadordabatata.png",
		"images/grass-sheet0.png",
		"images/solido1000porcento-sheet0.png",
		"images/balao-sheet0.png",
		"images/pressniga-sheet0.png",
		"images/locc-sheet0.png",
		"images/stage11-sheet0.png",
		"images/escreveakigiselle-sheet0.png",
		"images/tanoshiiicomomomo-sheet0.png",
		"images/didit-sheet0.png",
		"images/photoshoptopurify-sheet0.png",
		"images/felicias-sheet0.png",
		"media/jump_07.m4a",
		"media/jump_07.ogg",
		"media/no more magic.ogg",
		"media/menu selection click.m4a",
		"media/menu selection click.ogg",
		"media/grasslands theme (online-audio-converter.com).m4a",
		"media/grasslands theme (online-audio-converter.com).ogg",
		"media/boss theme (online-audio-converter.com).m4a",
		"media/boss theme (online-audio-converter.com).ogg",
		"media/hold the line_1.ogg",
		"media/pickup_coin.m4a",
		"media/pickup_coin.ogg",
		"media/skill_hit (online-audio-converter.com).m4a",
		"media/skill_hit (online-audio-converter.com).ogg",
		"media/momodorarutm.exe_000103.m4a",
		"media/momodorarutm.exe_000103.ogg",
		"media/07 - stage 5.m4a",
		"media/07 - stage 5.ogg",
		"media/11 - boss 1.m4a",
		"media/11 - boss 1.ogg",
		"media/12 - boss 2.m4a",
		"media/12 - boss 2.ogg",
		"media/21 - miss.m4a",
		"media/21 - miss.ogg",
		"media/19 - item get!.m4a",
		"media/19 - item get!.ogg",
		"media/22 - ending 1.m4a",
		"media/22 - ending 1.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}